# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'buying_tickets.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QApplication, QMainWindow, QPushButton,
                             QToolTip, QMessageBox, QLabel, QWidget)


class Ui_BuyingTicketsScreen(QMainWindow, object):
    def __init__(self, c, m):
        super().__init__()
        self.model = m
        self.controller = c

        BuyingTicketsScreen = QWidget()
        self.setObjectName("BuyingTicketsScreen")
        self.resize(500, 800)
        self.setStyleSheet("background-color: rgb(167, 191, 238);")
        self.centralwidget = QtWidgets.QWidget(BuyingTicketsScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 501, 81))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.top_layout = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.top_layout.setContentsMargins(10, 20, 10, 0)
        self.top_layout.setSpacing(50)
        self.top_layout.setObjectName("top_layout")
        self.back_top_but = QtWidgets.QPushButton(self.layoutWidget_2)
        self.back_top_but.setMinimumSize(QtCore.QSize(100, 60))
        self.back_top_but.setMaximumSize(QtCore.QSize(100, 16777215))
        self.back_top_but.setStyleSheet("background-color: #05668D;\n"
                                        "font: 15pt  \"Stencil\";\n"
                                        "color: white;")
        self.back_top_but.setObjectName("back_top_but")
        self.back_top_but.clicked.connect(lambda: self.controller.showUserTicketsScreen())

        self.top_layout.addWidget(self.back_top_but)
        self.buying_tickets_label_top = QtWidgets.QLabel(self.layoutWidget_2)
        self.buying_tickets_label_top.setMinimumSize(QtCore.QSize(331, 60))
        self.buying_tickets_label_top.setMaximumSize(QtCore.QSize(331, 60))
        self.buying_tickets_label_top.setStyleSheet("background-color: rgb(5, 102, 141);\n"
                                                    "font: 20pt \"Stencil\";\n"
                                                    "color: white;")
        self.buying_tickets_label_top.setObjectName("buying_tickets_label_top")
        self.top_layout.addWidget(self.buying_tickets_label_top)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 100, 500, 601))
        self.layoutWidget.setObjectName("layoutWidget")
        self.cental_block_layout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.cental_block_layout.setContentsMargins(15, 0, 15, 0)
        self.cental_block_layout.setSpacing(10)
        self.cental_block_layout.setObjectName("cental_block_layout")
        self.ticket_box_5 = QtWidgets.QGroupBox(self.layoutWidget)
        self.ticket_box_5.setMinimumSize(QtCore.QSize(470, 110))
        self.ticket_box_5.setMaximumSize(QtCore.QSize(470, 110))
        self.ticket_box_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                        "border: 5px solid;\n"
                                        "border-color: #FE938C;")
        self.ticket_box_5.setTitle("")
        self.ticket_box_5.setObjectName("ticket_box_5")
        self.layoutWidget_9 = QtWidgets.QWidget(self.ticket_box_5)
        self.layoutWidget_9.setGeometry(QtCore.QRect(11, 10, 451, 94))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_9)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.top_ticket_layout_5 = QtWidgets.QHBoxLayout()
        self.top_ticket_layout_5.setObjectName("top_ticket_layout_5")
        self.ticket_text_5 = QtWidgets.QLabel(self.layoutWidget_9)
        self.ticket_text_5.setMinimumSize(QtCore.QSize(100, 40))
        self.ticket_text_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ticket_text_5.setStyleSheet("font: 15pt \"Stencil\";\n"
                                         "color:  rgb(5, 102, 141);\n"
                                         "border: 0px;")
        self.ticket_text_5.setObjectName("ticket_text_5")
        self.top_ticket_layout_5.addWidget(self.ticket_text_5)
        self.ticket_number_label_5 = QtWidgets.QLabel(self.layoutWidget_9)
        self.ticket_number_label_5.setMinimumSize(QtCore.QSize(150, 40))
        self.ticket_number_label_5.setMaximumSize(QtCore.QSize(150, 16777215))
        self.ticket_number_label_5.setStyleSheet("font: 12pt \"Stencil\";\n"
                                                 "color:  rgb(5, 102, 141);\n"
                                                 "border: 0px;")
        self.ticket_number_label_5.setObjectName("ticket_number_label_5")
        self.top_ticket_layout_5.addWidget(self.ticket_number_label_5)
        self.ticket_number_less_button_5 = QtWidgets.QPushButton(self.layoutWidget_9)
        self.ticket_number_less_button_5.setMinimumSize(QtCore.QSize(31, 31))
        self.ticket_number_less_button_5.setMaximumSize(QtCore.QSize(31, 31))
        self.ticket_number_less_button_5.setStyleSheet("border: 5px solid;\n"
                                                       "font: 40pt  \"Stencil\";\n"
                                                       "color: #00A676;\n"
                                                       "border-color: rgb(254, 147, 140);")
        self.ticket_number_less_button_5.setObjectName("ticket_number_less_button_5")
        self.top_ticket_layout_5.addWidget(self.ticket_number_less_button_5)
        self.ticket_namber_info_5 = QtWidgets.QLabel(self.layoutWidget_9)
        self.ticket_namber_info_5.setMinimumSize(QtCore.QSize(80, 40))
        self.ticket_namber_info_5.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ticket_namber_info_5.setStyleSheet("font: 25pt \"Stencil\";\n"
                                                "color:  rgb(5, 102, 141);\n"
                                                "border: 0px;")
        self.ticket_namber_info_5.setObjectName("ticket_namber_info_5")
        self.top_ticket_layout_5.addWidget(self.ticket_namber_info_5)
        self.ticket_label_more_button_5 = QtWidgets.QPushButton(self.layoutWidget_9)
        self.ticket_label_more_button_5.setMinimumSize(QtCore.QSize(31, 31))
        self.ticket_label_more_button_5.setMaximumSize(QtCore.QSize(31, 31))
        self.ticket_label_more_button_5.setStyleSheet("border: 5px solid;\n"
                                                      "font: 40pt  \"Stencil\";\n"
                                                      "color: #00A676;\n"
                                                      "border-color: rgb(254, 147, 140);")
        self.ticket_label_more_button_5.setObjectName("ticket_label_more_button_5")
        self.top_ticket_layout_5.addWidget(self.ticket_label_more_button_5)
        self.verticalLayout_6.addLayout(self.top_ticket_layout_5)
        self.ticket_lower_layout_5 = QtWidgets.QHBoxLayout()
        self.ticket_lower_layout_5.setObjectName("ticket_lower_layout_5")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.date_info_5 = QtWidgets.QLabel(self.layoutWidget_9)
        self.date_info_5.setMinimumSize(QtCore.QSize(150, 40))
        self.date_info_5.setMaximumSize(QtCore.QSize(250, 16777215))
        self.date_info_5.setStyleSheet("font: 10pt \"Stencil\";\n"
                                       "color:  #00A676;\n"
                                       "border: 0px;")
        self.date_info_5.setObjectName("date_info_5")
        self.horizontalLayout_13.addWidget(self.date_info_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.ticket_lower_layout_5.addLayout(self.horizontalLayout_13)
        self.ticket_price_label_5 = QtWidgets.QLabel(self.layoutWidget_9)
        self.ticket_price_label_5.setMinimumSize(QtCore.QSize(200, 40))
        self.ticket_price_label_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ticket_price_label_5.setStyleSheet("background-color:#FFB627;\n"
                                                "font: 20pt  \"Stencil\";\n"
                                                "color: white;\n"
                                                "border: 0px;")
        self.ticket_price_label_5.setObjectName("ticket_price_label_5")
        self.ticket_lower_layout_5.addWidget(self.ticket_price_label_5)
        self.verticalLayout_6.addLayout(self.ticket_lower_layout_5)
        self.cental_block_layout.addWidget(self.ticket_box_5)
        self.ticket_box_4 = QtWidgets.QGroupBox(self.layoutWidget)
        self.ticket_box_4.setMinimumSize(QtCore.QSize(470, 110))
        self.ticket_box_4.setMaximumSize(QtCore.QSize(470, 110))
        self.ticket_box_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                        "border: 5px solid;\n"
                                        "border-color: #FE938C;")
        self.ticket_box_4.setTitle("")
        self.ticket_box_4.setObjectName("ticket_box_4")
        self.layoutWidget_8 = QtWidgets.QWidget(self.ticket_box_4)
        self.layoutWidget_8.setGeometry(QtCore.QRect(11, 10, 451, 94))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.top_ticket_layout_4 = QtWidgets.QHBoxLayout()
        self.top_ticket_layout_4.setObjectName("top_ticket_layout_4")
        self.ticket_text_4 = QtWidgets.QLabel(self.layoutWidget_8)
        self.ticket_text_4.setMinimumSize(QtCore.QSize(100, 40))
        self.ticket_text_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ticket_text_4.setStyleSheet("font: 15pt \"Stencil\";\n"
                                         "color:  rgb(5, 102, 141);\n"
                                         "border: 0px;")
        self.ticket_text_4.setObjectName("ticket_text_4")
        self.top_ticket_layout_4.addWidget(self.ticket_text_4)
        self.ticket_number_label_4 = QtWidgets.QLabel(self.layoutWidget_8)
        self.ticket_number_label_4.setMinimumSize(QtCore.QSize(150, 40))
        self.ticket_number_label_4.setMaximumSize(QtCore.QSize(150, 16777215))
        self.ticket_number_label_4.setStyleSheet("font: 12pt \"Stencil\";\n"
                                                 "color:  rgb(5, 102, 141);\n"
                                                 "border: 0px;")
        self.ticket_number_label_4.setObjectName("ticket_number_label_4")
        self.top_ticket_layout_4.addWidget(self.ticket_number_label_4)
        self.ticket_number_less_button_4 = QtWidgets.QPushButton(self.layoutWidget_8)
        self.ticket_number_less_button_4.setMinimumSize(QtCore.QSize(31, 31))
        self.ticket_number_less_button_4.setMaximumSize(QtCore.QSize(31, 31))
        self.ticket_number_less_button_4.setStyleSheet("border: 5px solid;\n"
                                                       "font: 40pt  \"Stencil\";\n"
                                                       "color: #00A676;\n"
                                                       "border-color: rgb(254, 147, 140);")
        self.ticket_number_less_button_4.setObjectName("ticket_number_less_button_4")
        self.top_ticket_layout_4.addWidget(self.ticket_number_less_button_4)
        self.ticket_namber_info_4 = QtWidgets.QLabel(self.layoutWidget_8)
        self.ticket_namber_info_4.setMinimumSize(QtCore.QSize(80, 40))
        self.ticket_namber_info_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ticket_namber_info_4.setStyleSheet("font: 25pt \"Stencil\";\n"
                                                "color:  rgb(5, 102, 141);\n"
                                                "border: 0px;")
        self.ticket_namber_info_4.setObjectName("ticket_namber_info_4")
        self.top_ticket_layout_4.addWidget(self.ticket_namber_info_4)
        self.ticket_label_more_button_4 = QtWidgets.QPushButton(self.layoutWidget_8)
        self.ticket_label_more_button_4.setMinimumSize(QtCore.QSize(31, 31))
        self.ticket_label_more_button_4.setMaximumSize(QtCore.QSize(31, 31))
        self.ticket_label_more_button_4.setStyleSheet("border: 5px solid;\n"
                                                      "font: 40pt  \"Stencil\";\n"
                                                      "color: #00A676;\n"
                                                      "border-color: rgb(254, 147, 140);")
        self.ticket_label_more_button_4.setObjectName("ticket_label_more_button_4")
        self.top_ticket_layout_4.addWidget(self.ticket_label_more_button_4)
        self.verticalLayout_5.addLayout(self.top_ticket_layout_4)
        self.ticket_lower_layout_4 = QtWidgets.QHBoxLayout()
        self.ticket_lower_layout_4.setObjectName("ticket_lower_layout_4")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.date_info_4 = QtWidgets.QLabel(self.layoutWidget_8)
        self.date_info_4.setMinimumSize(QtCore.QSize(150, 40))
        self.date_info_4.setMaximumSize(QtCore.QSize(250, 16777215))
        self.date_info_4.setStyleSheet("font: 10pt \"Stencil\";\n"
                                       "color:  #00A676;\n"
                                       "border: 0px;")
        self.date_info_4.setObjectName("date_info_4")
        self.horizontalLayout_12.addWidget(self.date_info_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.ticket_lower_layout_4.addLayout(self.horizontalLayout_12)
        self.ticket_price_label_4 = QtWidgets.QLabel(self.layoutWidget_8)
        self.ticket_price_label_4.setMinimumSize(QtCore.QSize(200, 40))
        self.ticket_price_label_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ticket_price_label_4.setStyleSheet("background-color:#FFB627;\n"
                                                "font: 20pt  \"Stencil\";\n"
                                                "color: white;\n"
                                                "border: 0px;")
        self.ticket_price_label_4.setObjectName("ticket_price_label_4")
        self.ticket_lower_layout_4.addWidget(self.ticket_price_label_4)
        self.verticalLayout_5.addLayout(self.ticket_lower_layout_4)
        self.cental_block_layout.addWidget(self.ticket_box_4)
        self.ticket_box_3 = QtWidgets.QGroupBox(self.layoutWidget)
        self.ticket_box_3.setMinimumSize(QtCore.QSize(470, 110))
        self.ticket_box_3.setMaximumSize(QtCore.QSize(470, 110))
        self.ticket_box_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                        "border: 5px solid;\n"
                                        "border-color: #FE938C;")
        self.ticket_box_3.setTitle("")
        self.ticket_box_3.setObjectName("ticket_box_3")
        self.layoutWidget_7 = QtWidgets.QWidget(self.ticket_box_3)
        self.layoutWidget_7.setGeometry(QtCore.QRect(11, 10, 451, 94))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.top_ticket_layout_3 = QtWidgets.QHBoxLayout()
        self.top_ticket_layout_3.setObjectName("top_ticket_layout_3")
        self.ticket_text_3 = QtWidgets.QLabel(self.layoutWidget_7)
        self.ticket_text_3.setMinimumSize(QtCore.QSize(100, 40))
        self.ticket_text_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ticket_text_3.setStyleSheet("font: 15pt \"Stencil\";\n"
                                         "color:  rgb(5, 102, 141);\n"
                                         "border: 0px;")
        self.ticket_text_3.setObjectName("ticket_text_3")
        self.top_ticket_layout_3.addWidget(self.ticket_text_3)
        self.ticket_number_label_3 = QtWidgets.QLabel(self.layoutWidget_7)
        self.ticket_number_label_3.setMinimumSize(QtCore.QSize(150, 40))
        self.ticket_number_label_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.ticket_number_label_3.setStyleSheet("font: 12pt \"Stencil\";\n"
                                                 "color:  rgb(5, 102, 141);\n"
                                                 "border: 0px;")
        self.ticket_number_label_3.setObjectName("ticket_number_label_3")
        self.top_ticket_layout_3.addWidget(self.ticket_number_label_3)
        self.ticket_number_less_button_3 = QtWidgets.QPushButton(self.layoutWidget_7)
        self.ticket_number_less_button_3.setMinimumSize(QtCore.QSize(31, 31))
        self.ticket_number_less_button_3.setMaximumSize(QtCore.QSize(31, 31))
        self.ticket_number_less_button_3.setStyleSheet("border: 5px solid;\n"
                                                       "font: 40pt  \"Stencil\";\n"
                                                       "color: #00A676;\n"
                                                       "border-color: rgb(254, 147, 140);")
        self.ticket_number_less_button_3.setObjectName("ticket_number_less_button_3")
        self.top_ticket_layout_3.addWidget(self.ticket_number_less_button_3)
        self.ticket_namber_info_3 = QtWidgets.QLabel(self.layoutWidget_7)
        self.ticket_namber_info_3.setMinimumSize(QtCore.QSize(80, 40))
        self.ticket_namber_info_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ticket_namber_info_3.setStyleSheet("font: 25pt \"Stencil\";\n"
                                                "color:  rgb(5, 102, 141);\n"
                                                "border: 0px;")
        self.ticket_namber_info_3.setObjectName("ticket_namber_info_3")
        self.top_ticket_layout_3.addWidget(self.ticket_namber_info_3)
        self.ticket_label_more_button_3 = QtWidgets.QPushButton(self.layoutWidget_7)
        self.ticket_label_more_button_3.setMinimumSize(QtCore.QSize(31, 31))
        self.ticket_label_more_button_3.setMaximumSize(QtCore.QSize(31, 31))
        self.ticket_label_more_button_3.setStyleSheet("border: 5px solid;\n"
                                                      "font: 40pt  \"Stencil\";\n"
                                                      "color: #00A676;\n"
                                                      "border-color: rgb(254, 147, 140);")
        self.ticket_label_more_button_3.setObjectName("ticket_label_more_button_3")
        self.top_ticket_layout_3.addWidget(self.ticket_label_more_button_3)
        self.verticalLayout_4.addLayout(self.top_ticket_layout_3)
        self.ticket_lower_layout_3 = QtWidgets.QHBoxLayout()
        self.ticket_lower_layout_3.setObjectName("ticket_lower_layout_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.date_info_3 = QtWidgets.QLabel(self.layoutWidget_7)
        self.date_info_3.setMinimumSize(QtCore.QSize(150, 40))
        self.date_info_3.setMaximumSize(QtCore.QSize(250, 16777215))
        self.date_info_3.setStyleSheet("font: 10pt \"Stencil\";\n"
                                       "color:  #00A676;\n"
                                       "border: 0px;")
        self.date_info_3.setObjectName("date_info_3")
        self.horizontalLayout_11.addWidget(self.date_info_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.ticket_lower_layout_3.addLayout(self.horizontalLayout_11)
        self.ticket_price_label_3 = QtWidgets.QLabel(self.layoutWidget_7)
        self.ticket_price_label_3.setMinimumSize(QtCore.QSize(200, 40))
        self.ticket_price_label_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ticket_price_label_3.setStyleSheet("background-color:#FFB627;\n"
                                                "font: 20pt  \"Stencil\";\n"
                                                "color: white;\n"
                                                "border: 0px;")
        self.ticket_price_label_3.setObjectName("ticket_price_label_3")
        self.ticket_lower_layout_3.addWidget(self.ticket_price_label_3)
        self.verticalLayout_4.addLayout(self.ticket_lower_layout_3)
        self.cental_block_layout.addWidget(self.ticket_box_3)
        self.ticket_box_2 = QtWidgets.QGroupBox(self.layoutWidget)
        self.ticket_box_2.setMinimumSize(QtCore.QSize(470, 110))
        self.ticket_box_2.setMaximumSize(QtCore.QSize(470, 110))
        self.ticket_box_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                        "border: 5px solid;\n"
                                        "border-color: #FE938C;")
        self.ticket_box_2.setTitle("")
        self.ticket_box_2.setObjectName("ticket_box_2")
        self.layoutWidget_6 = QtWidgets.QWidget(self.ticket_box_2)
        self.layoutWidget_6.setGeometry(QtCore.QRect(11, 10, 451, 94))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.top_ticket_layout_2 = QtWidgets.QHBoxLayout()
        self.top_ticket_layout_2.setObjectName("top_ticket_layout_2")
        self.ticket_text_2 = QtWidgets.QLabel(self.layoutWidget_6)
        self.ticket_text_2.setMinimumSize(QtCore.QSize(100, 40))
        self.ticket_text_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ticket_text_2.setStyleSheet("font: 15pt \"Stencil\";\n"
                                         "color:  rgb(5, 102, 141);\n"
                                         "border: 0px;")
        self.ticket_text_2.setObjectName("ticket_text_2")
        self.top_ticket_layout_2.addWidget(self.ticket_text_2)
        self.ticket_number_label_2 = QtWidgets.QLabel(self.layoutWidget_6)
        self.ticket_number_label_2.setMinimumSize(QtCore.QSize(150, 40))
        self.ticket_number_label_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.ticket_number_label_2.setStyleSheet("font: 12pt \"Stencil\";\n"
                                                 "color:  rgb(5, 102, 141);\n"
                                                 "border: 0px;")
        self.ticket_number_label_2.setObjectName("ticket_number_label_2")
        self.top_ticket_layout_2.addWidget(self.ticket_number_label_2)
        self.ticket_number_less_button_2 = QtWidgets.QPushButton(self.layoutWidget_6)
        self.ticket_number_less_button_2.setMinimumSize(QtCore.QSize(31, 31))
        self.ticket_number_less_button_2.setMaximumSize(QtCore.QSize(31, 31))
        self.ticket_number_less_button_2.setStyleSheet("border: 5px solid;\n"
                                                       "font: 40pt  \"Stencil\";\n"
                                                       "color: #00A676;\n"
                                                       "border-color: rgb(254, 147, 140);")
        self.ticket_number_less_button_2.setObjectName("ticket_number_less_button_2")
        self.top_ticket_layout_2.addWidget(self.ticket_number_less_button_2)
        self.ticket_namber_info_2 = QtWidgets.QLabel(self.layoutWidget_6)
        self.ticket_namber_info_2.setMinimumSize(QtCore.QSize(80, 40))
        self.ticket_namber_info_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ticket_namber_info_2.setStyleSheet("font: 25pt \"Stencil\";\n"
                                                "color:  rgb(5, 102, 141);\n"
                                                "border: 0px;")
        self.ticket_namber_info_2.setObjectName("ticket_namber_info_2")
        self.top_ticket_layout_2.addWidget(self.ticket_namber_info_2)
        self.ticket_label_more_button_2 = QtWidgets.QPushButton(self.layoutWidget_6)
        self.ticket_label_more_button_2.setMinimumSize(QtCore.QSize(31, 31))
        self.ticket_label_more_button_2.setMaximumSize(QtCore.QSize(31, 31))
        self.ticket_label_more_button_2.setStyleSheet("border: 5px solid;\n"
                                                      "font: 40pt  \"Stencil\";\n"
                                                      "color: #00A676;\n"
                                                      "border-color: rgb(254, 147, 140);")
        self.ticket_label_more_button_2.setObjectName("ticket_label_more_button_2")
        self.top_ticket_layout_2.addWidget(self.ticket_label_more_button_2)
        self.verticalLayout_3.addLayout(self.top_ticket_layout_2)
        self.ticket_lower_layout_2 = QtWidgets.QHBoxLayout()
        self.ticket_lower_layout_2.setObjectName("ticket_lower_layout_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.date_info_2 = QtWidgets.QLabel(self.layoutWidget_6)
        self.date_info_2.setMinimumSize(QtCore.QSize(150, 40))
        self.date_info_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.date_info_2.setStyleSheet("font: 10pt \"Stencil\";\n"
                                       "color:  #00A676;\n"
                                       "border: 0px;")
        self.date_info_2.setObjectName("date_info_2")
        self.horizontalLayout_10.addWidget(self.date_info_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.ticket_lower_layout_2.addLayout(self.horizontalLayout_10)
        self.ticket_price_label_2 = QtWidgets.QLabel(self.layoutWidget_6)
        self.ticket_price_label_2.setMinimumSize(QtCore.QSize(200, 40))
        self.ticket_price_label_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ticket_price_label_2.setStyleSheet("background-color:#FFB627;\n"
                                                "font: 20pt  \"Stencil\";\n"
                                                "color: white;\n"
                                                "border: 0px;")
        self.ticket_price_label_2.setObjectName("ticket_price_label_2")
        self.ticket_lower_layout_2.addWidget(self.ticket_price_label_2)
        self.verticalLayout_3.addLayout(self.ticket_lower_layout_2)
        self.cental_block_layout.addWidget(self.ticket_box_2)
        self.ticket_box = QtWidgets.QGroupBox(self.layoutWidget)
        self.ticket_box.setMinimumSize(QtCore.QSize(470, 110))
        self.ticket_box.setMaximumSize(QtCore.QSize(470, 110))
        self.ticket_box.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                      "border: 5px solid;\n"
                                      "border-color: #FE938C;")
        self.ticket_box.setTitle("")
        self.ticket_box.setObjectName("ticket_box")
        self.layoutWidget_5 = QtWidgets.QWidget(self.ticket_box)
        self.layoutWidget_5.setGeometry(QtCore.QRect(11, 10, 451, 94))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.top_ticket_layout = QtWidgets.QHBoxLayout()
        self.top_ticket_layout.setObjectName("top_ticket_layout")
        self.ticket_text = QtWidgets.QLabel(self.layoutWidget_5)
        self.ticket_text.setMinimumSize(QtCore.QSize(100, 40))
        self.ticket_text.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ticket_text.setStyleSheet("font: 15pt \"Stencil\";\n"
                                       "color:  rgb(5, 102, 141);\n"
                                       "border: 0px;")
        self.ticket_text.setObjectName("ticket_text")
        self.top_ticket_layout.addWidget(self.ticket_text)
        self.ticket_number_label = QtWidgets.QLabel(self.layoutWidget_5)
        self.ticket_number_label.setMinimumSize(QtCore.QSize(150, 40))
        self.ticket_number_label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.ticket_number_label.setStyleSheet("font: 12pt \"Stencil\";\n"
                                               "color:  rgb(5, 102, 141);\n"
                                               "border: 0px;")
        self.ticket_number_label.setObjectName("ticket_number_label")
        self.top_ticket_layout.addWidget(self.ticket_number_label)
        self.ticket_number_less_button = QtWidgets.QPushButton(self.layoutWidget_5)
        self.ticket_number_less_button.setMinimumSize(QtCore.QSize(31, 31))
        self.ticket_number_less_button.setMaximumSize(QtCore.QSize(31, 31))
        self.ticket_number_less_button.setStyleSheet("border: 5px solid;\n"
                                                     "font: 40pt  \"Stencil\";\n"
                                                     "color: #00A676;\n"
                                                     "border-color: rgb(254, 147, 140);")
        self.ticket_number_less_button.setObjectName("ticket_number_less_button")
        self.top_ticket_layout.addWidget(self.ticket_number_less_button)
        self.ticket_namber_info = QtWidgets.QLabel(self.layoutWidget_5)
        self.ticket_namber_info.setMinimumSize(QtCore.QSize(80, 40))
        self.ticket_namber_info.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ticket_namber_info.setStyleSheet("font: 25pt \"Stencil\";\n"
                                              "color:  rgb(5, 102, 141);\n"
                                              "border: 0px;")
        self.ticket_namber_info.setObjectName("ticket_namber_info")
        self.top_ticket_layout.addWidget(self.ticket_namber_info)
        self.ticket_label_more_button = QtWidgets.QPushButton(self.layoutWidget_5)
        self.ticket_label_more_button.setMinimumSize(QtCore.QSize(31, 31))
        self.ticket_label_more_button.setMaximumSize(QtCore.QSize(31, 31))
        self.ticket_label_more_button.setStyleSheet("border: 5px solid;\n"
                                                    "font: 40pt  \"Stencil\";\n"
                                                    "color: #00A676;\n"
                                                    "border-color: rgb(254, 147, 140);")
        self.ticket_label_more_button.setObjectName("ticket_label_more_button")
        self.top_ticket_layout.addWidget(self.ticket_label_more_button)
        self.verticalLayout_2.addLayout(self.top_ticket_layout)
        self.ticket_lower_layout = QtWidgets.QHBoxLayout()
        self.ticket_lower_layout.setObjectName("ticket_lower_layout")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.date_info = QtWidgets.QLabel(self.layoutWidget_5)
        self.date_info.setMinimumSize(QtCore.QSize(150, 40))
        self.date_info.setMaximumSize(QtCore.QSize(250, 16777215))
        self.date_info.setStyleSheet("font: 10pt \"Stencil\";\n"
                                     "color:  #00A676;\n"
                                     "border: 0px;")
        self.date_info.setObjectName("date_info")
        self.horizontalLayout_9.addWidget(self.date_info)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.ticket_lower_layout.addLayout(self.horizontalLayout_9)
        self.ticket_price_label = QtWidgets.QLabel(self.layoutWidget_5)
        self.ticket_price_label.setMinimumSize(QtCore.QSize(200, 40))
        self.ticket_price_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ticket_price_label.setStyleSheet("background-color:#FFB627;\n"
                                              "font: 20pt  \"Stencil\";\n"
                                              "color: white;\n"
                                              "border: 0px;")
        self.ticket_price_label.setObjectName("ticket_price_label")
        self.ticket_lower_layout.addWidget(self.ticket_price_label)
        self.verticalLayout_2.addLayout(self.ticket_lower_layout)
        self.cental_block_layout.addWidget(self.ticket_box)
        self.footer_box_for_summ = QtWidgets.QGroupBox(self.centralwidget)
        self.footer_box_for_summ.setGeometry(QtCore.QRect(0, 710, 500, 70))
        self.footer_box_for_summ.setMinimumSize(QtCore.QSize(500, 70))
        self.footer_box_for_summ.setMaximumSize(QtCore.QSize(500, 70))
        self.footer_box_for_summ.setStyleSheet("background-color:#FFB627;\n"
                                               "font: 20pt  \"Stencil\";\n"
                                               "color: white;\n"
                                               "border: 0px;")
        self.footer_box_for_summ.setTitle("")
        self.footer_box_for_summ.setObjectName("footer_box_for_summ")
        self.layoutWidget1 = QtWidgets.QWidget(self.footer_box_for_summ)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 481, 42))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.sum_label = QtWidgets.QLabel(self.layoutWidget1)
        self.sum_label.setMinimumSize(QtCore.QSize(50, 40))
        self.sum_label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.sum_label.setStyleSheet("font: 25pt \"Stencil\";\n"
                                     "color:  rgb(5, 102, 141);\n"
                                     "border: 0px;")
        self.sum_label.setObjectName("sum_label")
        self.horizontalLayout_22.addWidget(self.sum_label)
        self.sum_info = QtWidgets.QLabel(self.layoutWidget1)
        self.sum_info.setMinimumSize(QtCore.QSize(100, 40))
        self.sum_info.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sum_info.setStyleSheet("font: 25pt \"Stencil\";\n"
                                    "color:  rgb(5, 102, 141);\n"
                                    "border: 0px;")
        self.sum_info.setObjectName("sum_info")
        self.horizontalLayout_22.addWidget(self.sum_info)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem5)
        self.pay_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.pay_button.setMinimumSize(QtCore.QSize(100, 40))
        self.pay_button.setStyleSheet("background-color:  rgb(5, 102, 141);\n"
                                      "font: 15pt  \"Stencil\";\n"
                                      "color: white;")
        self.pay_button.setObjectName("pay_button")
        self.horizontalLayout_22.addWidget(self.pay_button)
        self.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(BuyingTicketsScreen)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("BuyingTicketsScreen", "WaterWorld"))
        self.back_top_but.setText(_translate("BuyingTicketsScreen", "< BACK"))
        self.buying_tickets_label_top.setText(_translate("BuyingTicketsScreen", "BUYING TICKETS"))
        self.ticket_text_5.setText(_translate("BuyingTicketsScreen", "TEXT"))
        self.ticket_number_label_5.setText(_translate("BuyingTicketsScreen", "TICKETS NUMBER:"))
        self.ticket_number_less_button_5.setText(_translate("BuyingTicketsScreen", "-"))
        self.ticket_namber_info_5.setText(_translate("BuyingTicketsScreen", "TEXT"))
        self.ticket_label_more_button_5.setText(_translate("BuyingTicketsScreen", "+"))
        self.date_info_5.setText(_translate("BuyingTicketsScreen", "date text"))
        self.ticket_price_label_5.setText(_translate("BuyingTicketsScreen", "<price>"))
        self.ticket_text_4.setText(_translate("BuyingTicketsScreen", "TEXT"))
        self.ticket_number_label_4.setText(_translate("BuyingTicketsScreen", "TICKETS NUMBER:"))
        self.ticket_number_less_button_4.setText(_translate("BuyingTicketsScreen", "-"))
        self.ticket_namber_info_4.setText(_translate("BuyingTicketsScreen", "TEXT"))
        self.ticket_label_more_button_4.setText(_translate("BuyingTicketsScreen", "+"))
        self.date_info_4.setText(_translate("BuyingTicketsScreen", "date text"))
        self.ticket_price_label_4.setText(_translate("BuyingTicketsScreen", "<price>"))
        self.ticket_text_3.setText(_translate("BuyingTicketsScreen", "TEXT"))
        self.ticket_number_label_3.setText(_translate("BuyingTicketsScreen", "TICKETS NUMBER:"))
        self.ticket_number_less_button_3.setText(_translate("BuyingTicketsScreen", "-"))
        self.ticket_namber_info_3.setText(_translate("BuyingTicketsScreen", "TEXT"))
        self.ticket_label_more_button_3.setText(_translate("BuyingTicketsScreen", "+"))
        self.date_info_3.setText(_translate("BuyingTicketsScreen", "date text"))
        self.ticket_price_label_3.setText(_translate("BuyingTicketsScreen", "<price>"))
        self.ticket_text_2.setText(_translate("BuyingTicketsScreen", "TEXT"))
        self.ticket_number_label_2.setText(_translate("BuyingTicketsScreen", "TICKETS NUMBER:"))
        self.ticket_number_less_button_2.setText(_translate("BuyingTicketsScreen", "-"))
        self.ticket_namber_info_2.setText(_translate("BuyingTicketsScreen", "TEXT"))
        self.ticket_label_more_button_2.setText(_translate("BuyingTicketsScreen", "+"))
        self.date_info_2.setText(_translate("BuyingTicketsScreen", "date text"))
        self.ticket_price_label_2.setText(_translate("BuyingTicketsScreen", "<price>"))
        self.ticket_text.setText(_translate("BuyingTicketsScreen", "TEXT"))
        self.ticket_number_label.setText(_translate("BuyingTicketsScreen", "TICKETS NUMBER:"))
        self.ticket_number_less_button.setText(_translate("BuyingTicketsScreen", "-"))
        self.ticket_namber_info.setText(_translate("BuyingTicketsScreen", "TEXT"))
        self.ticket_label_more_button.setText(_translate("BuyingTicketsScreen", "+"))
        self.date_info.setText(_translate("BuyingTicketsScreen", "date text"))
        self.ticket_price_label.setText(_translate("BuyingTicketsScreen", "<price>"))
        self.sum_label.setText(_translate("BuyingTicketsScreen", "SUM:"))
        self.sum_info.setText(_translate("BuyingTicketsScreen", "TEXT"))
        self.pay_button.setText(_translate("BuyingTicketsScreen", "PAY FOR TICKETS"))

