# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_account.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QApplication, QMainWindow, QPushButton,
                             QToolTip, QMessageBox, QLabel, QWidget)


class Ui_CreateAccWindow(QMainWindow, object):
    def __init__(self, c, m):
        super().__init__()
        self.model = m
        self.controller = c

        CreateAccWindow = QWidget()
        self.setObjectName("CreateAccWindow")
        self.resize(500, 800)
        self.setStyleSheet("background-color: rgb(167, 191, 238);")

        self.centralwidget = QtWidgets.QWidget(CreateAccWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 501, 801))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(50)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.Icon_image_layout = QtWidgets.QHBoxLayout()
        self.Icon_image_layout.setObjectName("Icon_image_layout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Icon_image_layout.addItem(spacerItem1)
        self.image_label = QtWidgets.QLabel(self.layoutWidget)
        self.image_label.setMinimumSize(QtCore.QSize(131, 131))
        self.image_label.setText("")
        self.image_label.setPixmap(QtGui.QPixmap("../../../Users/nikit/Downloads/image (36).png"))
        self.image_label.setObjectName("image_label")
        self.Icon_image_layout.addWidget(self.image_label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Icon_image_layout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.Icon_image_layout)
        self.Label_layout = QtWidgets.QHBoxLayout()
        self.Label_layout.setObjectName("Label_layout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Label_layout.addItem(spacerItem3)
        self.create_acc_label = QtWidgets.QLabel(self.layoutWidget)
        self.create_acc_label.setMinimumSize(QtCore.QSize(370, 50))
        self.create_acc_label.setStyleSheet("background-color: rgb(5, 102, 141);\n"
                                            "font: 36pt \"Stencil\";\n"
                                            "color: white;")
        self.create_acc_label.setObjectName("create_acc_label")
        self.Label_layout.addWidget(self.create_acc_label)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Label_layout.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.Label_layout)
        self.enter_fields_layout = QtWidgets.QHBoxLayout()
        self.enter_fields_layout.setSpacing(0)
        self.enter_fields_layout.setObjectName("enter_fields_layout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.enter_fields_layout.addItem(spacerItem5)
        self.edit_fields_layout = QtWidgets.QVBoxLayout()
        self.edit_fields_layout.setSpacing(30)
        self.edit_fields_layout.setObjectName("edit_fields_layout")
        self.enter_mail_phone_edit_field_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.enter_mail_phone_edit_field_2.setMinimumSize(QtCore.QSize(300, 70))
        self.enter_mail_phone_edit_field_2.setStyleSheet("border: 5px solid;\n"
                                                         "border-color: #FFB627;\n"
                                                         "background-color: rgb(255, 255, 255);\n"
                                                         "font: 10pt \"Stencil\";\n"
                                                         "color: gray;\n"
                                                         "")
        self.enter_mail_phone_edit_field_2.setObjectName("enter_mail_phone_edit_field_2")
        self.edit_fields_layout.addWidget(self.enter_mail_phone_edit_field_2)
        self.enter_password_edit_field = QtWidgets.QLineEdit(self.layoutWidget)
        self.enter_password_edit_field.setMinimumSize(QtCore.QSize(300, 70))
        self.enter_password_edit_field.setStyleSheet("border: 5px solid;\n"
                                                     "border-color: #FFB627;\n"
                                                     "background-color: rgb(255, 255, 255);\n"
                                                     "font: 10pt \"Stencil\";\n"
                                                     "color: gray;\n"
                                                     "")
        self.enter_password_edit_field.setObjectName("enter_password_edit_field")
        self.edit_fields_layout.addWidget(self.enter_password_edit_field)
        self.enter_fields_layout.addLayout(self.edit_fields_layout)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.enter_fields_layout.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.enter_fields_layout)
        self.buttons_layout = QtWidgets.QHBoxLayout()
        self.buttons_layout.setSpacing(40)
        self.buttons_layout.setObjectName("buttons_layout")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttons_layout.addItem(spacerItem7)
        self.back_but = QtWidgets.QPushButton(self.layoutWidget)
        self.back_but.setMinimumSize(QtCore.QSize(100, 60))
        self.back_but.setStyleSheet("background-color: rgb(254, 147, 140);\n"
                                    "font: 20pt  \"Stencil\";\n"
                                    "color: white;")
        self.back_but.setObjectName("back_but")
        self.back_but.clicked.connect(lambda: self.controller.showMainScreen())

        self.buttons_layout.addWidget(self.back_but)
        self.login_but = QtWidgets.QPushButton(self.layoutWidget)
        self.login_but.setMinimumSize(QtCore.QSize(100, 60))
        self.login_but.setStyleSheet("background-color: rgb(254, 147, 140);\n"
                                     "font: 20pt  \"Stencil\";\n"
                                     "color: white;")
        self.login_but.setObjectName("login_but")
        self.login_but.clicked.connect(lambda: self.login())

        self.buttons_layout.addWidget(self.login_but)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttons_layout.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.buttons_layout)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem9)
        self.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)


        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(CreateAccWindow)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("CreateAccWindow", "WaterWorld"))
        self.create_acc_label.setText(_translate("CreateAccWindow", "CREATE ACCOUNT"))
        self.enter_mail_phone_edit_field_2.setText(_translate("CreateAccWindow", "Enter e-mail or ph. number..."))
        self.enter_password_edit_field.setText(_translate("CreateAccWindow", "Enter password..."))
        self.back_but.setText(_translate("CreateAccWindow", "BACK"))
        self.login_but.setText(_translate("CreateAccWindow", "LOG IN"))

    def login(self):
        self.controller.createAcc(self.enter_password_edit_field.text(), self.enter_password_edit_field.text())
