# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deletion_dialogue.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QApplication, QMainWindow, QPushButton,
                             QToolTip, QMessageBox, QLabel, QWidget, QDialog)


class Ui_Dialog(QDialog, object):
    def __init__(self, c, m):
        super().__init__()
        self.model = m
        self.controller = c

        self.setObjectName("Dialog")
        self.resize(400, 300)
        self.groupBox = QtWidgets.QGroupBox(self)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 400, 300))
        self.groupBox.setMinimumSize(QtCore.QSize(400, 300))
        self.groupBox.setMaximumSize(QtCore.QSize(400, 300))
        self.groupBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border: 5px solid;\n"
                                    "border-color: #FE938C;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 11, 381, 281))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setMinimumSize(QtCore.QSize(220, 40))
        self.label_13.setMaximumSize(QtCore.QSize(220, 16777215))
        self.label_13.setStyleSheet("font: 12pt \"Stencil\";\n"
                                    "color:  rgb(5, 102, 141);\n"
                                    "border: 0px;")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setMinimumSize(QtCore.QSize(111, 31))
        self.checkBox.setMaximumSize(QtCore.QSize(111, 31))
        self.checkBox.setStyleSheet("border: 0px;\n"
                                    "background-color: #FFB627;\n"
                                    "font: 10pt \"Stencil\";\n"
                                    "color:white;\n"
                                    "")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox)
        self.checkBox_4 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_4.setMinimumSize(QtCore.QSize(111, 31))
        self.checkBox_4.setMaximumSize(QtCore.QSize(111, 31))
        self.checkBox_4.setStyleSheet("border: 0px;\n"
                                      "background-color: #FFB627;\n"
                                      "font: 10pt \"Stencil\";\n"
                                      "color:white;\n"
                                      "")
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_3.addWidget(self.checkBox_4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_2.setMinimumSize(QtCore.QSize(111, 31))
        self.checkBox_2.setMaximumSize(QtCore.QSize(111, 31))
        self.checkBox_2.setStyleSheet("border: 0px;\n"
                                      "background-color: #FFB627;\n"
                                      "font: 10pt \"Stencil\";\n"
                                      "color:white;\n"
                                      "")
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_4.addWidget(self.checkBox_2)
        self.checkBox_5 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_5.setMinimumSize(QtCore.QSize(111, 31))
        self.checkBox_5.setMaximumSize(QtCore.QSize(111, 31))
        self.checkBox_5.setStyleSheet("border: 0px;\n"
                                      "background-color: #FFB627;\n"
                                      "font: 10pt \"Stencil\";\n"
                                      "color:white;\n"
                                      "")
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_4.addWidget(self.checkBox_5)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_3.setMinimumSize(QtCore.QSize(111, 31))
        self.checkBox_3.setMaximumSize(QtCore.QSize(111, 31))
        self.checkBox_3.setStyleSheet("border: 0px;\n"
                                      "background-color: #FFB627;\n"
                                      "font: 10pt \"Stencil\";\n"
                                      "color:white;\n"
                                      "")
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_5.addWidget(self.checkBox_3)
        self.checkBox_6 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_6.setMinimumSize(QtCore.QSize(111, 31))
        self.checkBox_6.setMaximumSize(QtCore.QSize(111, 31))
        self.checkBox_6.setStyleSheet("border: 0px;\n"
                                      "background-color: #FFB627;\n"
                                      "font: 10pt \"Stencil\";\n"
                                      "color:white;\n"
                                      "")
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout_5.addWidget(self.checkBox_6)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.sendReviewButton = QtWidgets.QPushButton(self.widget)
        self.sendReviewButton.setMinimumSize(QtCore.QSize(100, 40))
        self.sendReviewButton.setStyleSheet("background-color: rgb(254, 147, 140);\n"
                                            "font: 15pt  \"Stencil\";\n"
                                            "color: white;")
        self.sendReviewButton.setObjectName("sendReviewButton")
        self.horizontalLayout.addWidget(self.sendReviewButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_13.setText(_translate("Dialog", "CHOOSE DELETION REASONS"))
        self.checkBox.setText(_translate("Dialog", "not true"))
        self.checkBox_4.setText(_translate("Dialog", "porn distr."))
        self.checkBox_2.setText(_translate("Dialog", "insult"))
        self.checkBox_5.setText(_translate("Dialog", "overdue"))
        self.checkBox_3.setText(_translate("Dialog", "spam"))
        self.checkBox_6.setText(_translate("Dialog", "rasism"))
        self.sendReviewButton.setText(_translate("Dialog", "SEND"))

