# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'location_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QApplication, QMainWindow, QPushButton,
                             QToolTip, QMessageBox, QLabel, QWidget)


class Ui_LocationScreen(QMainWindow, object):
    def __init__(self, c, m):
        super().__init__()
        self.model = m
        self.controller = c
        self.location = None

        LocationScreen = QWidget()
        self.setObjectName("LocationScreen")
        self.resize(500, 800)
        self.setStyleSheet("background-color: rgb(167, 191, 238);")
        self.centralwidget = QtWidgets.QWidget(LocationScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 501, 81))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.top_layout = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.top_layout.setContentsMargins(10, 20, 10, 0)
        self.top_layout.setSpacing(50)
        self.top_layout.setObjectName("top_layout")
        self.back_top_but = QtWidgets.QPushButton(self.layoutWidget_2)
        self.back_top_but.setMinimumSize(QtCore.QSize(100, 60))
        self.back_top_but.setMaximumSize(QtCore.QSize(100, 16777215))
        self.back_top_but.setStyleSheet("background-color: #05668D;\n"
                                        "font: 15pt  \"Stencil\";\n"
                                        "color: white;")
        self.back_top_but.setObjectName("back_top_but")
        self.back_top_but.clicked.connect(lambda: self.controller.showMenuScreen())

        self.top_layout.addWidget(self.back_top_but)
        self.attraction_name_label_top = QtWidgets.QLabel(self.layoutWidget_2)
        self.attraction_name_label_top.setMinimumSize(QtCore.QSize(331, 60))
        self.attraction_name_label_top.setMaximumSize(QtCore.QSize(331, 60))
        self.attraction_name_label_top.setStyleSheet("background-color: rgb(5, 102, 141);\n"
                                                     "font: 20pt \"Stencil\";\n"
                                                     "color: white;")
        self.attraction_name_label_top.setObjectName("attraction_name_label_top")
        self.top_layout.addWidget(self.attraction_name_label_top)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(1, 90, 501, 234))
        self.layoutWidget.setObjectName("layoutWidget")
        self.location_info_central_layout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.location_info_central_layout.setContentsMargins(0, 0, 0, 0)
        self.location_info_central_layout.setObjectName("location_info_central_layout")
        self.left_location_info_layout = QtWidgets.QVBoxLayout()
        self.left_location_info_layout.setObjectName("left_location_info_layout")
        self.location_image = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.location_image.sizePolicy().hasHeightForWidth())
        self.location_image.setSizePolicy(sizePolicy)
        self.location_image.setMinimumSize(QtCore.QSize(210, 120))
        self.location_image.setMaximumSize(QtCore.QSize(210, 120))
        self.location_image.setText("")
        self.location_image.setPixmap(QtGui.QPixmap("../../../Users/nikit/Downloads/39.png"))
        self.location_image.setObjectName("location_image")
        self.left_location_info_layout.addWidget(self.location_image)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.left_location_info_layout.addItem(spacerItem)
        self.location_info_central_layout.addLayout(self.left_location_info_layout)
        self.right_location_info_layout = QtWidgets.QVBoxLayout()
        self.right_location_info_layout.setObjectName("right_location_info_layout")
        self.location_name_label = QtWidgets.QLabel(self.layoutWidget)
        self.location_name_label.setMinimumSize(QtCore.QSize(250, 40))
        self.location_name_label.setMaximumSize(QtCore.QSize(250, 16777215))
        self.location_name_label.setStyleSheet("font: 30pt \"Stencil\";\n"
                                               "color:  rgb(5, 102, 141);")
        self.location_name_label.setObjectName("location_name_label")
        self.right_location_info_layout.addWidget(self.location_name_label)
        self.description_label = QtWidgets.QLabel(self.layoutWidget)
        self.description_label.setMinimumSize(QtCore.QSize(250, 50))
        self.description_label.setMaximumSize(QtCore.QSize(250, 16777215))
        self.description_label.setStyleSheet("font: 12pt \"Stencil\";\n"
                                             "color: white;\n"
                                             "border: 5px solid;\n"
                                             "border-color: rgb(254, 147, 140);")
        self.description_label.setObjectName("description_label")
        self.right_location_info_layout.addWidget(self.description_label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.location_1_layout = QtWidgets.QHBoxLayout()
        self.location_1_layout.setObjectName("location_1_layout")
        self.location_parametr1_label = QtWidgets.QLabel(self.layoutWidget)
        self.location_parametr1_label.setMinimumSize(QtCore.QSize(150, 20))
        self.location_parametr1_label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.location_parametr1_label.setStyleSheet("font: 15pt \"Stencil\";\n"
                                                    "color: #00A676;")
        self.location_parametr1_label.setObjectName("location_parametr1_label")
        self.location_1_layout.addWidget(self.location_parametr1_label)
        spacerItem1 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.location_1_layout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.location_1_layout)
        self.location_2_layout = QtWidgets.QHBoxLayout()
        self.location_2_layout.setObjectName("location_2_layout")
        self.location_parametr2_label = QtWidgets.QLabel(self.layoutWidget)
        self.location_parametr2_label.setMinimumSize(QtCore.QSize(150, 20))
        self.location_parametr2_label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.location_parametr2_label.setStyleSheet("font: 15pt \"Stencil\";\n"
                                                    "color: #00A676;")
        self.location_parametr2_label.setObjectName("location_parametr2_label")
        self.location_2_layout.addWidget(self.location_parametr2_label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.location_2_layout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.location_2_layout)
        self.location_3_layout = QtWidgets.QHBoxLayout()
        self.location_3_layout.setObjectName("location_3_layout")
        self.location_parametr3_label = QtWidgets.QLabel(self.layoutWidget)
        self.location_parametr3_label.setMinimumSize(QtCore.QSize(150, 20))
        self.location_parametr3_label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.location_parametr3_label.setStyleSheet("font: 15pt \"Stencil\";\n"
                                                    "color: #00A676;")
        self.location_parametr3_label.setObjectName("location_parametr3_label")
        self.location_3_layout.addWidget(self.location_parametr3_label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.location_3_layout.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.location_3_layout)
        self.leave_review_layout = QtWidgets.QHBoxLayout()
        self.leave_review_layout.setObjectName("leave_review_layout")
        self.leave_review_button = QtWidgets.QPushButton(self.layoutWidget)
        self.leave_review_button.setMinimumSize(QtCore.QSize(150, 40))
        self.leave_review_button.setMaximumSize(QtCore.QSize(150, 40))
        self.leave_review_button.setStyleSheet("border: 5px solid;\n"
                                               "font: 12pt  \"Stencil\";\n"
                                               "color: #00A676;\n"
                                               "border-color: rgb(254, 147, 140);\n")
        self.leave_review_button.setObjectName("leave_review_button")
        self.leave_review_button.clicked.connect(lambda: self.controller.showReviewDialogue())

        self.leave_review_layout.addWidget(self.leave_review_button)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.leave_review_layout.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.leave_review_layout)
        self.right_location_info_layout.addLayout(self.verticalLayout_2)
        self.location_info_central_layout.addLayout(self.right_location_info_layout)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 340, 501, 451))
        self.widget.setObjectName("widget")
        self.reviews_layout = QtWidgets.QVBoxLayout(self.widget)
        self.reviews_layout.setContentsMargins(0, 0, 0, 0)
        self.reviews_layout.setObjectName("reviews_layout")
        self.location_review_layout = QtWidgets.QHBoxLayout()
        self.location_review_layout.setObjectName("location_review_layout")
        self.location_review_label = QtWidgets.QLabel(self.widget)
        self.location_review_label.setMinimumSize(QtCore.QSize(250, 40))
        self.location_review_label.setMaximumSize(QtCore.QSize(250, 16777215))
        self.location_review_label.setStyleSheet("border: 0px; font: 30pt \"Stencil\";\n"
                                                 "color:  rgb(5, 102, 141);\n"
                                                 "border: 0px;")
        self.location_review_label.setObjectName("location_review_label")
        self.location_review_layout.addWidget(self.location_review_label)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.location_review_layout.addItem(spacerItem5)
        self.reviews_layout.addLayout(self.location_review_layout)
        self.review_scroll_area = QtWidgets.QScrollArea(self.widget)
        self.review_scroll_area.setWidgetResizable(True)
        self.review_scroll_area.setObjectName("review_scroll_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 497, 392))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.one_review_box = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.one_review_box.setGeometry(QtCore.QRect(0, 0, 481, 131))
        self.one_review_box.setStyleSheet("border-bottom:5px solid;\n"
                                          "border-color:#FFB627;")
        self.one_review_box.setTitle("")
        self.one_review_box.setObjectName("one_review_box")
        self.layoutWidget1 = QtWidgets.QWidget(self.one_review_box)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 10, 480, 112))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.review_content_layout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.review_content_layout.setContentsMargins(0, 0, 0, 0)
        self.review_content_layout.setObjectName("review_content_layout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.top_review_layout = QtWidgets.QHBoxLayout()
        self.top_review_layout.setObjectName("top_review_layout")
        self.review_user_name = QtWidgets.QLabel(self.layoutWidget1)
        self.review_user_name.setMinimumSize(QtCore.QSize(200, 30))
        self.review_user_name.setMaximumSize(QtCore.QSize(200, 30))
        self.review_user_name.setStyleSheet("font: 20pt \"Stencil\";\n"
                                            "color: #00A676;\n"
                                            "border: 0px;")
        self.review_user_name.setObjectName("review_user_name")
        self.top_review_layout.addWidget(self.review_user_name)
        spacerItem6 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.top_review_layout.addItem(spacerItem6)
        self.edit_review_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.edit_review_button.setStyleSheet("border: 5px solid;\n"
                                              "font: 12pt  \"Stencil\";\n"
                                              "color: #00A676;\n"
                                              "border-color: rgb(254, 147, 140);")
        self.edit_review_button.setObjectName("edit_review_button")
        self.top_review_layout.addWidget(self.edit_review_button)
        self.delete_review_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.delete_review_button.setStyleSheet("border: 5px solid;\n"
                                                "font: 12pt  \"Stencil\";\n"
                                                "color: #00A676;\n"
                                                "border-color: rgb(254, 147, 140);")
        self.delete_review_button.setObjectName("delete_review_button")
        self.top_review_layout.addWidget(self.delete_review_button)
        self.verticalLayout_4.addLayout(self.top_review_layout)
        self.review_text = QtWidgets.QLabel(self.layoutWidget1)
        self.review_text.setMinimumSize(QtCore.QSize(430, 70))
        self.review_text.setMaximumSize(QtCore.QSize(430, 70))
        self.review_text.setStyleSheet("font: 12pt \"Stencil\";\n"
                                       "color: white;\n"
                                       "border: 5px solid;\n"
                                       "border-color: rgb(254, 147, 140);")
        self.review_text.setObjectName("review_text")
        self.verticalLayout_4.addWidget(self.review_text)
        self.review_content_layout.addLayout(self.verticalLayout_4)

        self.delete_with_reason_review_button = QtWidgets.QPushButton(self.layoutWidget)
        self.delete_with_reason_review_button.setMinimumSize(QtCore.QSize(31, 31))
        self.delete_with_reason_review_button.setMaximumSize(QtCore.QSize(31, 31))
        self.delete_with_reason_review_button.setStyleSheet("border: 5px solid;\n"
                                                            "font: 40pt  \"Stencil\";\n"
                                                            "color: #00A676;\n"
                                                            "border-color: rgb(254, 147, 140);")
        self.delete_with_reason_review_button.setObjectName("delete_with_reason_review_button")
        self.delete_with_reason_review_button.clicked.connect(lambda: self.controller.showDeletionDialogue())

        self.review_content_layout.addWidget(self.delete_with_reason_review_button)
        self.review_scroll_area.setWidget(self.scrollAreaWidgetContents)
        self.reviews_layout.addWidget(self.review_scroll_area)
        self.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(LocationScreen)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("LocationScreen", "WaterWorld"))
        self.back_top_but.setText(_translate("LocationScreen", "< BACK"))
        self.attraction_name_label_top.setText(_translate("LocationScreen", "<ATT NAME>"))
        self.location_name_label.setText(_translate("LocationScreen", "TEXT"))
        self.description_label.setText(_translate("LocationScreen", "TEXT"))
        self.location_parametr1_label.setText(_translate("LocationScreen", "TEXT"))
        self.location_parametr2_label.setText(_translate("LocationScreen", "TEXT"))
        self.location_parametr3_label.setText(_translate("LocationScreen", "TEXT"))
        self.leave_review_button.setText(_translate("LocationScreen", "LEAVE REVIEW"))
        self.location_review_label.setText(_translate("LocationScreen", "REVIEWS"))
        self.review_user_name.setText(_translate("LocationScreen", "<user name>"))
        self.edit_review_button.setText(_translate("LocationScreen", "EDIT"))
        self.delete_review_button.setText(_translate("LocationScreen", "DELETE"))
        self.review_text.setText(_translate("LocationScreen", "TEXT"))
        self.delete_with_reason_review_button.setText(_translate("LocationScreen", "-"))

    def setLoc(self, location):
        self.location = location
