# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'locations_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QApplication, QMainWindow, QPushButton,
                             QToolTip, QMessageBox, QLabel, QWidget)


class Ui_LocationsScreen(QMainWindow, object):
    def __init__(self, c, m):
        super().__init__()
        self.model = m
        self.controller = c
        self.type = None

        LocationsScreen = QWidget()
        self.setObjectName("LocationsScreen")
        self.resize(500, 800)
        self.setStyleSheet("background-color: rgb(167, 191, 238);")

        self.centralwidget = QtWidgets.QWidget(LocationsScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 501, 81))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.top_layout = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.top_layout.setContentsMargins(10, 20, 10, 0)
        self.top_layout.setSpacing(50)
        self.top_layout.setObjectName("top_layout")
        self.back_top_but = QtWidgets.QPushButton(self.layoutWidget_2)
        self.back_top_but.setMinimumSize(QtCore.QSize(100, 60))
        self.back_top_but.setMaximumSize(QtCore.QSize(100, 16777215))
        self.back_top_but.setStyleSheet("background-color: #05668D;\n"
                                        "font: 15pt  \"Stencil\";\n"
                                        "color: white;")
        self.back_top_but.setObjectName("back_top_but")
        self.back_top_but.clicked.connect(lambda: self.controller.showMenuScreen())

        self.top_layout.addWidget(self.back_top_but)
        self.top_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.top_label.setMinimumSize(QtCore.QSize(331, 60))
        self.top_label.setMaximumSize(QtCore.QSize(331, 16777215))
        self.top_label.setStyleSheet("background-color: rgb(5, 102, 141);\n"
                                     "font: 36pt \"Stencil\";\n"
                                     "color: white;")
        self.top_label.setObjectName("top_label")
        self.top_layout.addWidget(self.top_label)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 100, 500, 700))
        self.scrollArea.setMinimumSize(QtCore.QSize(500, 700))
        self.scrollArea.setMaximumSize(QtCore.QSize(500, 700))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 498, 698))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.layoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 501, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.one_location_layout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.one_location_layout.setContentsMargins(0, 0, 0, 0)
        self.one_location_layout.setObjectName("one_location_layout")
        self.location_image = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.location_image.sizePolicy().hasHeightForWidth())
        self.location_image.setSizePolicy(sizePolicy)
        self.location_image.setMinimumSize(QtCore.QSize(210, 120))
        self.location_image.setMaximumSize(QtCore.QSize(210, 120))
        self.location_image.setText("")
        self.location_image.setPixmap(QtGui.QPixmap("../../../Users/nikit/Downloads/39.png"))
        self.location_image.setObjectName("location_image")
        self.one_location_layout.addWidget(self.location_image)
        self.BoxLayout = QtWidgets.QVBoxLayout()
        self.BoxLayout.setObjectName("0")
        self.location_name_label = QtWidgets.QLabel(self.layoutWidget)
        self.location_name_label.setMinimumSize(QtCore.QSize(250, 40))
        self.location_name_label.setMaximumSize(QtCore.QSize(250, 16777215))
        self.location_name_label.setStyleSheet("font: 30pt \"Stencil\";\n"
                                               "color:  rgb(5, 102, 141);")
        self.location_name_label.setObjectName("location_name_label")
        self.BoxLayout.addWidget(self.location_name_label)
        self.location_1_layout = QtWidgets.QHBoxLayout()
        self.location_1_layout.setObjectName("location_1_layout")
        self.location_parametr1_label = QtWidgets.QLabel(self.layoutWidget)
        self.location_parametr1_label.setMinimumSize(QtCore.QSize(150, 20))
        self.location_parametr1_label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.location_parametr1_label.setStyleSheet("font: 15pt \"Stencil\";\n"
                                                    "color: #00A676;")
        self.location_parametr1_label.setObjectName("location_parametr1_label")
        self.location_1_layout.addWidget(self.location_parametr1_label)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.location_1_layout.addItem(spacerItem)
        self.BoxLayout.addLayout(self.location_1_layout)
        self.location_2_layout = QtWidgets.QHBoxLayout()
        self.location_2_layout.setObjectName("location_2_layout")
        self.location_parametr2_label = QtWidgets.QLabel(self.layoutWidget)
        self.location_parametr2_label.setMinimumSize(QtCore.QSize(150, 20))
        self.location_parametr2_label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.location_parametr2_label.setStyleSheet("font: 15pt \"Stencil\";\n"
                                                    "color: #00A676;")
        self.location_parametr2_label.setObjectName("location_parametr2_label")
        self.location_2_layout.addWidget(self.location_parametr2_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.location_2_layout.addItem(spacerItem1)
        self.BoxLayout.addLayout(self.location_2_layout)
        self.location_3_layout = QtWidgets.QHBoxLayout()
        self.location_3_layout.setObjectName("location_3_layout")
        self.location_parametr3_label = QtWidgets.QLabel(self.layoutWidget)
        self.location_parametr3_label.setMinimumSize(QtCore.QSize(150, 20))
        self.location_parametr3_label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.location_parametr3_label.setStyleSheet("font: 15pt \"Stencil\";\n"
                                                    "color: #00A676;")
        self.location_parametr3_label.setObjectName("location_parametr3_label")
        self.location_3_layout.addWidget(self.location_parametr3_label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.location_3_layout.addItem(spacerItem2)

        self.more_location_but = QtWidgets.QPushButton(self.layoutWidget)
        self.more_location_but.setMinimumSize(QtCore.QSize(70, 30))
        self.more_location_but.setMaximumSize(QtCore.QSize(70, 30))
        self.more_location_but.setStyleSheet("border: 5px solid;\n"
                                             "font: 10pt  \"Stencil\";\n"
                                             "color: #00A676;\n"
                                             "border-color: rgb(254, 147, 140);")
        self.more_location_but.setObjectName("more_location_but")
        self.more_location_but.clicked.connect(lambda: self.controller. showLocationScreen(1))



        self.location_3_layout.addWidget(self.more_location_but)
        self.BoxLayout.addLayout(self.location_3_layout)
        self.one_location_layout.addLayout(self.BoxLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(LocationsScreen)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("LocationsScreen", "WaterWorld"))
        self.back_top_but.setText(_translate("LocationsScreen", "< BACK"))
        self.top_label.setText(_translate("LocationsScreen", "TEXT"))
        self.location_name_label.setText(_translate("LocationsScreen", "TEXT"))
        self.location_parametr1_label.setText(_translate("LocationsScreen", "TEXT"))
        self.location_parametr2_label.setText(_translate("LocationsScreen", "TEXT"))
        self.location_parametr3_label.setText(_translate("LocationsScreen", "TEXT"))
        self.more_location_but.setText(_translate("LocationsScreen", "MORE"))

    def set_type(self, t):
        self.type = t