# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QApplication, QMainWindow, QPushButton,
                             QToolTip, QMessageBox, QLabel, QWidget)


class Ui_MainWindow(QMainWindow, object):
    def __init__(self, c, m):
        super().__init__()
        self.model = m
        self.controller = c

        MainWindow = QWidget()
        self.setObjectName("MainWindow")
        self.resize(500, 800)
        self.setStyleSheet("background-color: rgb(167, 191, 238);")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(1, 1, 501, 791))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(50)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.Icon_image_layout = QtWidgets.QHBoxLayout()
        self.Icon_image_layout.setObjectName("Icon_image_layout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Icon_image_layout.addItem(spacerItem1)
        self.image_label = QtWidgets.QLabel(self.layoutWidget)
        self.image_label.setMinimumSize(QtCore.QSize(131, 131))
        self.image_label.setText("")
        self.image_label.setPixmap(QtGui.QPixmap("../../../Users/nikit/Downloads/image (36).png"))
        self.image_label.setObjectName("image_label")
        self.Icon_image_layout.addWidget(self.image_label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Icon_image_layout.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.Icon_image_layout)
        self.button_layout = QtWidgets.QHBoxLayout()
        self.button_layout.setSpacing(30)
        self.button_layout.setObjectName("button_layout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.button_layout.addItem(spacerItem3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(30)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.login_but = QtWidgets.QPushButton(self.layoutWidget)
        self.login_but.setMinimumSize(QtCore.QSize(250, 60))
        self.login_but.setStyleSheet("background-color: rgb(254, 147, 140);\n"
                                     "font: 20pt  \"Stencil\";\n"
                                     "color: white;")
        self.login_but.setObjectName("login_but")
        self.verticalLayout_2.addWidget(self.login_but)
        self.create_acc_button = QtWidgets.QPushButton(self.layoutWidget)
        self.create_acc_button.setMinimumSize(QtCore.QSize(250, 60))
        self.create_acc_button.setStyleSheet("background-color: rgb(254, 147, 140);\n"
                                             "font: 20pt  \"Stencil\";\n"
                                             "color: white;")
        self.create_acc_button.setObjectName("create_acc_button")
        self.verticalLayout_2.addWidget(self.create_acc_button)
        self.button_layout.addLayout(self.verticalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.button_layout.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.button_layout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.create_acc_button.clicked.connect(lambda: self.controller.showCreateAccScreen())
        self.login_but.clicked.connect(lambda: self.controller.showEnterAccScreen())

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "WaterWorld"))
        self.login_but.setText(_translate("MainWindow", "LOG IN"))
        self.create_acc_button.setText(_translate("MainWindow", "CREATE ACCOUNT"))
