# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QApplication, QMainWindow, QPushButton,
                             QToolTip, QMessageBox, QLabel, QWidget)


class Ui_mainMenu(QMainWindow, object):
    def __init__(self, c, m):
        super().__init__()
        self.model = m
        self.controller = c

        mainMenu = QWidget()
        self.setObjectName("mainMenu")
        self.resize(500, 800)
        self.setStyleSheet("background-color: rgb(167, 191, 238);")

        self.centralwidget = QtWidgets.QWidget(mainMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 501, 791))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Label_layout = QtWidgets.QHBoxLayout()
        self.Label_layout.setObjectName("Label_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Label_layout.addItem(spacerItem)
        self.screen_label = QtWidgets.QLabel(self.layoutWidget)
        self.screen_label.setMinimumSize(QtCore.QSize(331, 50))
        self.screen_label.setStyleSheet("background-color: rgb(5, 102, 141);\n"
                                        "font: 36pt \"Stencil\";\n"
                                        "color: white;")
        self.screen_label.setObjectName("screen_label")
        self.Label_layout.addWidget(self.screen_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Label_layout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.Label_layout)
        self.image_layout = QtWidgets.QHBoxLayout()
        self.image_layout.setObjectName("image_layout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.image_layout.addItem(spacerItem2)
        self.image = QtWidgets.QLabel(self.layoutWidget)
        self.image.setMinimumSize(QtCore.QSize(300, 300))
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap("View/img/39.png"))
        self.image.setObjectName("image")
        self.image_layout.addWidget(self.image)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.image_layout.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.image_layout)
        self.button_layout = QtWidgets.QHBoxLayout()
        self.button_layout.setObjectName("button_layout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.button_layout.addItem(spacerItem4)
        self.about_button = QtWidgets.QPushButton(self.layoutWidget)
        self.about_button.setMinimumSize(QtCore.QSize(140, 60))
        self.about_button.setStyleSheet("background-color: rgb(254, 147, 140);\n"
                                        "font: 20pt  \"Stencil\";\n"
                                        "color: white;")
        self.about_button.setObjectName("about_button")
        self.about_button.clicked.connect(lambda: self.controller.showParkScreen())

        self.button_layout.addWidget(self.about_button)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.button_layout.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.button_layout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(20, 250, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.buttons_totom_layout = QtWidgets.QHBoxLayout()
        self.buttons_totom_layout.setSpacing(20)
        self.buttons_totom_layout.setObjectName("buttons_totom_layout")
        spacerItem7 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttons_totom_layout.addItem(spacerItem7)
        self.attractions_button = QtWidgets.QPushButton(self.layoutWidget)
        self.attractions_button.setMinimumSize(QtCore.QSize(150, 60))
        self.attractions_button.setStyleSheet("background-color: #05668D;\n"
                                              "font: 15pt  \"Stencil\";\n"
                                              "color: white;")
        self.attractions_button.setObjectName("attractions_button")
        self.attractions_button.clicked.connect(lambda: self.controller.showAttractionsScreen())

        self.buttons_totom_layout.addWidget(self.attractions_button)
        self.personal_button = QtWidgets.QPushButton(self.layoutWidget)
        self.personal_button.setMinimumSize(QtCore.QSize(110, 60))
        self.personal_button.setStyleSheet("background-color: #05668D;\n"
                                           "font: 15pt  \"Stencil\";\n"
                                           "color: white;")
        self.personal_button.setObjectName("personal_button")
        self.personal_button.clicked.connect(lambda: self.controller.showPersonalScreen())

        self.buttons_totom_layout.addWidget(self.personal_button)
        self.cafes_button = QtWidgets.QPushButton(self.layoutWidget)
        self.cafes_button.setMinimumSize(QtCore.QSize(150, 60))
        self.cafes_button.setStyleSheet("background-color: #05668D;\n"
                                        "font: 15pt  \"Stencil\";\n"
                                        "color: white;")
        self.cafes_button.setObjectName("cafes_button")
        self.cafes_button.clicked.connect(lambda: self.controller.showFoodPlacesScreen())

        self.buttons_totom_layout.addWidget(self.cafes_button)
        spacerItem8 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttons_totom_layout.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.buttons_totom_layout)
        spacerItem9 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(mainMenu)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("mainMenu", "WaterWorld"))
        self.screen_label.setText(_translate("mainMenu", "WATER WORLD"))
        self.about_button.setText(_translate("mainMenu", "ABOUT"))
        self.attractions_button.setText(_translate("mainMenu", "ATTRACTIONS"))
        self.personal_button.setText(_translate("mainMenu", "PERSONAL"))
        self.cafes_button.setText(_translate("mainMenu", "CAFES "))

