# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'review_dialogue.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QApplication, QMainWindow, QPushButton,
                             QToolTip, QMessageBox, QLabel, QWidget, QDialog)


class Ui_Dialog1(QDialog, object):
    def __init__(self, c, m):
        super().__init__()
        self.model = m
        self.controller = c

        self.setObjectName("Dialog")
        self.resize(400, 300)
        self.groupBox = QtWidgets.QGroupBox(self)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 400, 300))
        self.groupBox.setMinimumSize(QtCore.QSize(400, 300))
        self.groupBox.setMaximumSize(QtCore.QSize(400, 300))
        self.groupBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border: 5px solid;\n"
                                    "border-color: #FE938C;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 10, 381, 281))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setMinimumSize(QtCore.QSize(230, 40))
        self.label_13.setMaximumSize(QtCore.QSize(230, 16777215))
        self.label_13.setStyleSheet("font: 25pt \"Stencil\";\n"
                                    "color:  rgb(5, 102, 141);\n"
                                    "border: 0px;")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.reviewTextField = QtWidgets.QLineEdit(self.widget)
        self.reviewTextField.setMinimumSize(QtCore.QSize(300, 170))
        self.reviewTextField.setMaximumSize(QtCore.QSize(400, 170))
        self.reviewTextField.setStyleSheet("border: 5px solid;\n"
                                           "border-color: #FFB627;\n"
                                           "background-color: rgb(255, 255, 255);\n"
                                           "font: 10pt \"Stencil\";\n"
                                           "color: gray;\n"
                                           "")
        self.reviewTextField.setObjectName("reviewTextField")
        self.verticalLayout.addWidget(self.reviewTextField)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.sendReviewButton = QtWidgets.QPushButton(self.widget)
        self.sendReviewButton.setMinimumSize(QtCore.QSize(100, 40))
        self.sendReviewButton.setStyleSheet("background-color: rgb(254, 147, 140);\n"
                                            "font: 15pt  \"Stencil\";\n"
                                            "color: white;")
        self.sendReviewButton.setObjectName("sendReviewButton")
        self.horizontalLayout.addWidget(self.sendReviewButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_13.setText(_translate("Dialog", "Leave Review"))
        self.reviewTextField.setText(_translate("Dialog", "Enter text..."))
        self.sendReviewButton.setText(_translate("Dialog", "SEND"))

