# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tickets_history.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QApplication, QMainWindow, QPushButton,
                             QToolTip, QMessageBox, QLabel, QWidget)

class Ui_userTicketsStoryScreen(QMainWindow, object):
    def __init__(self, c, m):
        super().__init__()
        self.model = m
        self.controller = c
        self.user = None


        userTicketsStoryScreen = QWidget()
        self.setObjectName("userTicketsStoryScreen")
        self.resize(500, 800)
        self.setStyleSheet("background-color: rgb(167, 191, 238);")
        self.centralwidget = QtWidgets.QWidget(userTicketsStoryScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 501, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.top_layout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.top_layout.setContentsMargins(10, 20, 10, 0)
        self.top_layout.setSpacing(50)
        self.top_layout.setObjectName("top_layout")
        self.back_top_but = QtWidgets.QPushButton(self.layoutWidget)
        self.back_top_but.setMinimumSize(QtCore.QSize(100, 60))
        self.back_top_but.setMaximumSize(QtCore.QSize(100, 16777215))
        self.back_top_but.setStyleSheet("background-color: #05668D;\n"
                                        "font: 15pt  \"Stencil\";\n"
                                        "color: white;")
        self.back_top_but.setObjectName("back_top_but")
        self.back_top_but.clicked.connect(lambda: self.controller.showUserSearchScreen())

        self.top_layout.addWidget(self.back_top_but)
        self.user_tickets_label_top = QtWidgets.QLabel(self.layoutWidget)
        self.user_tickets_label_top.setMinimumSize(QtCore.QSize(331, 60))
        self.user_tickets_label_top.setMaximumSize(QtCore.QSize(331, 60))
        self.user_tickets_label_top.setStyleSheet("background-color: rgb(5, 102, 141);\n"
                                                  "font: 20pt \"Stencil\";\n"
                                                  "color: white;")
        self.user_tickets_label_top.setObjectName("user_tickets_label_top")
        self.top_layout.addWidget(self.user_tickets_label_top)
        self.user_tickets_scroll_area = QtWidgets.QScrollArea(self.centralwidget)
        self.user_tickets_scroll_area.setGeometry(QtCore.QRect(0, 130, 501, 671))
        self.user_tickets_scroll_area.setWidgetResizable(True)
        self.user_tickets_scroll_area.setObjectName("user_tickets_scroll_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 499, 669))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.one_user_ticket_box = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.one_user_ticket_box.setGeometry(QtCore.QRect(20, 10, 470, 160))
        self.one_user_ticket_box.setMinimumSize(QtCore.QSize(470, 160))
        self.one_user_ticket_box.setMaximumSize(QtCore.QSize(470, 160))
        self.one_user_ticket_box.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                               "border: 5px solid;\n"
                                               "border-color: #FE938C;")
        self.one_user_ticket_box.setTitle("")
        self.one_user_ticket_box.setObjectName("one_user_ticket_box")
        self.layoutWidget1 = QtWidgets.QWidget(self.one_user_ticket_box)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 448, 144))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ticket_top_layout = QtWidgets.QHBoxLayout()
        self.ticket_top_layout.setObjectName("ticket_top_layout")
        self.ticket_name_label = QtWidgets.QLabel(self.layoutWidget1)
        self.ticket_name_label.setMinimumSize(QtCore.QSize(200, 40))
        self.ticket_name_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ticket_name_label.setStyleSheet("font: 25pt \"Stencil\";\n"
                                             "color:  rgb(5, 102, 141);\n"
                                             "border: 0px;")
        self.ticket_name_label.setObjectName("ticket_name_label")
        self.ticket_top_layout.addWidget(self.ticket_name_label)
        self.number_layout = QtWidgets.QHBoxLayout()
        self.number_layout.setObjectName("number_layout")
        self.number_label = QtWidgets.QLabel(self.layoutWidget1)
        self.number_label.setMinimumSize(QtCore.QSize(150, 40))
        self.number_label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.number_label.setStyleSheet("font: 25pt \"Stencil\";\n"
                                        "color:  rgb(5, 102, 141);\n"
                                        "border: 0px;")
        self.number_label.setObjectName("number_label")
        self.number_layout.addWidget(self.number_label)
        self.number_info = QtWidgets.QLabel(self.layoutWidget1)
        self.number_info.setMinimumSize(QtCore.QSize(80, 40))
        self.number_info.setMaximumSize(QtCore.QSize(80, 16777215))
        self.number_info.setStyleSheet("font: 25pt \"Stencil\";\n"
                                       "color:  rgb(5, 102, 141);\n"
                                       "border: 0px;")
        self.number_info.setObjectName("number_info")
        self.number_layout.addWidget(self.number_info)
        self.ticket_top_layout.addLayout(self.number_layout)
        self.verticalLayout.addLayout(self.ticket_top_layout)
        self.date_layout = QtWidgets.QHBoxLayout()
        self.date_layout.setObjectName("date_layout")
        self.date_info = QtWidgets.QLabel(self.layoutWidget1)
        self.date_info.setMinimumSize(QtCore.QSize(150, 40))
        self.date_info.setMaximumSize(QtCore.QSize(250, 16777215))
        self.date_info.setStyleSheet("font: 10pt \"Stencil\";\n"
                                     "color:  #00A676;\n"
                                     "border: 0px;")
        self.date_info.setObjectName("date_info")
        self.date_layout.addWidget(self.date_info)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.date_layout.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.status_label = QtWidgets.QLabel(self.layoutWidget1)
        self.status_label.setMinimumSize(QtCore.QSize(150, 40))
        self.status_label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.status_label.setStyleSheet("font: 25pt \"Stencil\";\n"
                                        "color:  rgb(5, 102, 141);\n"
                                        "border: 0px;")
        self.status_label.setObjectName("status_label")
        self.horizontalLayout_4.addWidget(self.status_label)
        self.status_info = QtWidgets.QLabel(self.layoutWidget1)
        self.status_info.setMinimumSize(QtCore.QSize(80, 40))
        self.status_info.setMaximumSize(QtCore.QSize(80, 16777215))
        self.status_info.setStyleSheet("font: 25pt \"Stencil\";\n"
                                       "color:  rgb(5, 102, 141);\n"
                                       "border: 0px;")
        self.status_info.setObjectName("status_info")
        self.horizontalLayout_4.addWidget(self.status_info)
        self.date_layout.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.date_layout)
        self.buttons_layout = QtWidgets.QHBoxLayout()
        self.buttons_layout.setObjectName("buttons_layout")

        self.change_status_but = QtWidgets.QPushButton(self.layoutWidget1)
        self.change_status_but.setMinimumSize(QtCore.QSize(100, 40))
        self.change_status_but.setStyleSheet("background-color: rgb(254, 147, 140);\n"
                                             "font: 15pt  \"Stencil\";\n"
                                             "color: white;")
        self.change_status_but.setObjectName("change_status_but")
        self.change_status_but.clicked.connect(lambda: self.controller.showTicketStatusDialogue())

        self.buttons_layout.addWidget(self.change_status_but)
        self.verticalLayout.addLayout(self.buttons_layout)
        self.user_tickets_scroll_area.setWidget(self.scrollAreaWidgetContents)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 80, 501, 32))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.user_name_pretop_layout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.user_name_pretop_layout.setContentsMargins(0, 0, 0, 0)
        self.user_name_pretop_layout.setObjectName("user_name_pretop_layout")
        self.user_name_label_top = QtWidgets.QLabel(self.layoutWidget2)
        self.user_name_label_top.setMinimumSize(QtCore.QSize(200, 30))
        self.user_name_label_top.setMaximumSize(QtCore.QSize(200, 30))
        self.user_name_label_top.setStyleSheet("font: 20pt \"Stencil\";\n"
                                               "color: #00A676;\n"
                                               "border: 0px;")
        self.user_name_label_top.setObjectName("user_name_label_top")
        self.user_name_pretop_layout.addWidget(self.user_name_label_top)
        spacerItem1 = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.user_name_pretop_layout.addItem(spacerItem1)
        self.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(userTicketsStoryScreen)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("userTicketsStoryScreen", "WaterWorld"))
        self.back_top_but.setText(_translate("userTicketsStoryScreen", "< BACK"))
        self.user_tickets_label_top.setText(_translate("userTicketsStoryScreen", "USER\'S TICKETS HISTORY"))
        self.ticket_name_label.setText(_translate("userTicketsStoryScreen", "TEXT"))
        self.number_label.setText(_translate("userTicketsStoryScreen", "Number:"))
        self.number_info.setText(_translate("userTicketsStoryScreen", "TEXT"))
        self.date_info.setText(_translate("userTicketsStoryScreen", "date text"))
        self.status_label.setText(_translate("userTicketsStoryScreen", "STATUS:"))
        self.status_info.setText(_translate("userTicketsStoryScreen", "TEXT"))
        self.change_status_but.setText(_translate("userTicketsStoryScreen", "CHANGE STATUS"))
        self.user_name_label_top.setText(_translate("userTicketsStoryScreen", "<user name>"))


    def setUser(self, login):
        self.user = login
