# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_search.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QApplication, QMainWindow, QPushButton,
                             QToolTip, QMessageBox, QLabel, QWidget)


class Ui_userSearchWindow(QMainWindow, object):
    def __init__(self, c, m):
        super().__init__()
        self.model = m
        self.controller = c

        userSearchWindow = QWidget()
        self.setObjectName("userSearchWindow")
        self.resize(500, 800)
        self.setStyleSheet("background-color: rgb(167, 191, 238);")
        self.centralwidget = QtWidgets.QWidget(userSearchWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(2, 2, 503, 791))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(200)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.top_layout = QtWidgets.QHBoxLayout()
        self.top_layout.setContentsMargins(10, 20, 10, -1)
        self.top_layout.setSpacing(50)
        self.top_layout.setObjectName("top_layout")
        self.back_top_but = QtWidgets.QPushButton(self.layoutWidget)
        self.back_top_but.setMinimumSize(QtCore.QSize(100, 60))
        self.back_top_but.setMaximumSize(QtCore.QSize(100, 16777215))
        self.back_top_but.setStyleSheet("background-color: #05668D;\n"
                                        "font: 15pt  \"Stencil\";\n"
                                        "color: white;")
        self.back_top_but.setObjectName("back_top_but")
        self.back_top_but.clicked.connect(lambda: self.controller.showMenuScreen())

        self.top_layout.addWidget(self.back_top_but)
        self.top_label_user_management = QtWidgets.QLabel(self.layoutWidget)
        self.top_label_user_management.setMinimumSize(QtCore.QSize(331, 60))
        self.top_label_user_management.setMaximumSize(QtCore.QSize(331, 60))
        self.top_label_user_management.setStyleSheet("background-color: rgb(5, 102, 141);\n"
                                                     "font: 27pt \"Stencil\";\n"
                                                     "color: white;")
        self.top_label_user_management.setObjectName("top_label_user_management")
        self.top_layout.addWidget(self.top_label_user_management)
        self.verticalLayout_2.addLayout(self.top_layout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Label_layout = QtWidgets.QHBoxLayout()
        self.Label_layout.setObjectName("Label_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Label_layout.addItem(spacerItem)
        self.visitor_search_label = QtWidgets.QLabel(self.layoutWidget)
        self.visitor_search_label.setMinimumSize(QtCore.QSize(370, 50))
        self.visitor_search_label.setStyleSheet("background-color: rgb(5, 102, 141);\n"
                                                "font: 36pt \"Stencil\";\n"
                                                "color: white;")
        self.visitor_search_label.setObjectName("visitor_search_label")
        self.Label_layout.addWidget(self.visitor_search_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Label_layout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.Label_layout)
        self.enter_password_edit_field_layout = QtWidgets.QHBoxLayout()
        self.enter_password_edit_field_layout.setObjectName("enter_password_edit_field_layout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.enter_password_edit_field_layout.addItem(spacerItem2)
        self.enter_mail_edit_field = QtWidgets.QLineEdit(self.layoutWidget)
        self.enter_mail_edit_field.setMinimumSize(QtCore.QSize(300, 70))
        self.enter_mail_edit_field.setStyleSheet("border: 5px solid;\n"
                                                 "border-color: #FFB627;\n"
                                                 "background-color: rgb(255, 255, 255);\n"
                                                 "font: 10pt \"Stencil\";\n"
                                                 "color: gray;\n"
                                                 "")
        self.enter_mail_edit_field.setObjectName("enter_mail_edit_field")
        self.enter_password_edit_field_layout.addWidget(self.enter_mail_edit_field)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.enter_password_edit_field_layout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.enter_password_edit_field_layout)
        self.find_button_layout = QtWidgets.QHBoxLayout()
        self.find_button_layout.setObjectName("find_button_layout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.find_button_layout.addItem(spacerItem4)
        self.find_but = QtWidgets.QPushButton(self.layoutWidget)
        self.find_but.setMinimumSize(QtCore.QSize(100, 60))
        self.find_but.setStyleSheet("background-color: rgb(254, 147, 140);\n"
                                    "font: 20pt  \"Stencil\";\n"
                                    "color: white;")
        self.find_but.setObjectName("find_but")
        self.find_but.clicked.connect(lambda: self.controller.showTicketsHistoryScreen(self.enter_mail_edit_field.text()))

        self.find_button_layout.addWidget(self.find_but)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.find_button_layout.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.find_button_layout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(userSearchWindow)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("userSearchWindow", "WaterWorld"))
        self.back_top_but.setText(_translate("userSearchWindow", "< BACK"))
        self.top_label_user_management.setText(_translate("userSearchWindow", "USER MANAGEMENT"))
        self.visitor_search_label.setText(_translate("userSearchWindow", "VISITOR SEARCH"))
        self.enter_mail_edit_field.setText(_translate("userSearchWindow", "Enter e-mail or ph. number..."))
        self.find_but.setText(_translate("userSearchWindow", "FIND"))
